backend:
  name: github
  repo: ninfaj/oevplus-ch
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "Home"
    label: "Home"
    folder: "content/home"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Intro",
          name: "intro",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Text", name: "text", widget: "markdown" },
              { label: "Button Label", name: "buttonLabel", widget: "string" },
              { label: "Button Link", name: "buttonHref", widget: "string" },
            ],
        }
      - {
          label: "Carousel",
          name: "carousel",
          widget: "list",
          collapsed: true,
          summary: "{{fields.title}}",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              { label: "Text", name: "text", widget: "markdown" },
              {
                label: "Image",
                name: "image",
                widget: "image",
                chooseUrl: false,
              },
              { label: "LinkHref", name: "linkHref", widget: "string" },
              { label: "LinkLabel", name: "linkLabel", widget: "string" },
            ],
        }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "About"
    label: "About"
    folder: "content/about"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Intro",
          name: "intro",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Text", name: "text", widget: "markdown" },
              { label: "Button Label", name: "buttonLabel", widget: "string" },
              { label: "Button Link", name: "buttonHref", widget: "string" },
            ],
        }
      - {
          label: "TUS",
          name: "tus",
          widget: "list",
          collapsed: true,
          summary: "{{fields.title}}",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              {
                label: "Image",
                name: "image",
                widget: "image",
                chooseUrl: false,
              },
              { label: "url", name: "url", widget: "string" },
            ],
        }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "App"
    label: "App"
    folder: "content/app"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Intro",
          name: "intro",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Text", name: "text", widget: "markdown" },
              { label: "Button Label", name: "buttonLabel", widget: "string" },
              { label: "Button Link", name: "buttonHref", widget: "string" },
            ],
        }
      - { label: "Content", name: "body", widget: "markdown" }
      - {
          label: "Videos",
          name: "video",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              { label: "Text", name: "text", widget: "markdown" },
              {
                label: "Videos",
                name: "items",
                widget: "list",
                summary: "{{fields.title}}",
                fields:
                  [
                    { label: "Title", name: "title", widget: "string" },
                    { label: "Video", name: "video", widget: "file", choose_url: false },
                  ],
              },
            ],
        }
      - {
          label: "FAQ",
          name: "faq",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              { label: "Text", name: "text", widget: "markdown" },
              {
                label: "Items",
                name: "items",
                widget: "list",
                summary: "{{fields.title}}",
                fields:
                  [
                    { label: "Title", name: "title", widget: "string" },
                    { label: "Text", name: "text", widget: "markdown" },
                  ],
              },
            ],
        }

  - name: "Contact"
    label: "Contact"
    folder: "content/contact"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
      - {
          label: "Labels",
          name: "labels",
          create: false,
          delete: false,
          collapsed: false,
          widget: "list",
          summary: "{{fields.id}}",
          fields:
            [
              { label: "ID", name: "id", widget: "hidden" },
              { label: "Title", name: "title", widget: "string" },
            ],
        }