backend:
  name: github
  repo: ninfaj/oevplus-ch
  branch: master # Branch to update (optional; defaults to master)
locale: 'de'
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "Home"
    label: "Home"
    folder: "content/home"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Intro",
          name: "intro",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Text", name: "text", widget: "markdown" },
              { label: "Button Label", name: "buttonLabel", widget: "string" },
              { label: "Button Link", name: "buttonHref", widget: "string" },
            ],
        }
      - {
          label: "Carousel",
          name: "carousel",
          widget: "list",
          collapsed: true,
          summary: "{{fields.title}}",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              { label: "Text", name: "text", widget: "markdown" },
              {
                label: "Image",
                name: "image",
                widget: "image",
                choose_url: false,
              },
              { label: "LinkHref", name: "linkHref", widget: "string" },
              { label: "LinkLabel", name: "linkLabel", widget: "string" },
            ],
        }
      - {
          label: "Services",
          name: "services",
          widget: "object",
          collapsed: true,
          summary: "{{fields.title}}",
          fields:
            [
              {label: Title, name: "title", widget: "string"},
              {label: Text, name: "text", widget: "markdown"},
              {
                label: "Items",
                name: "items",
                collapsed: true,
                widget: "list",
                fields:
                  [
                    { label: "Title", name: "title", widget: "string" },
                    { label: "Text", name: "text", widget: "markdown" },
                    { label: "Image", name: "image", widget: "image", choose_url: false },
                    { label: "LinkHref", name: "linkHref", widget: "string" },
                    { label: "LinkLabel", name: "linkLabel", widget: "string" },
                  ]
              }
            ]
        }
      - { label: "Content", name: "body", widget: "markdown" }
      - {
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        required: false
        }
      - {
        label: "SEO Description",
        name: "summary",
        widget: "text",
        required: false
        }
      - {
        label: "SEO Keywords",
        name: "seoKeywords",
        widget: "string",
        required: false
        }

  - name: "About"
    label: "About"
    folder: "content/about"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Intro",
          name: "intro",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Text", name: "text", widget: "markdown" }
            ],
        }
      - {
          label: "TUS",
          name: "tus",
          widget: "list",
          collapsed: true,
          summary: "{{fields.title}}",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              {
                label: "Image",
                name: "image",
                widget: "image",
                choose_url: false,
              },
              { label: "url", name: "url", widget: "string" },
            ],
        }
      - { label: "Content", name: "body", widget: "markdown" }
      - {
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        required: false
        }
      - {
        label: "SEO Description",
        name: "summary",
        widget: "text",
        required: false
        }
      - {
        label: "SEO Keywords",
        name: "seoKeywords",
        widget: "string",
        required: false
        }

  - name: "App"
    label: "App"
    folder: "content/app"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Intro",
          name: "intro",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Text", name: "text", widget: "markdown" },
              { label: "Button Label", name: "buttonLabel", widget: "string" },
              { label: "Button Link", name: "buttonHref", widget: "string" },
              { label: "Link Android", name: "appLinkAndroid", widget: "string", required: false },
              { label: "Link iOS", name: "appLinkIOS", widget: "string", required: false },
            ],
        }
      - { label: "Content", name: "body", widget: "markdown" }
      - {
          label: "Videos",
          name: "video",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              { label: "Text", name: "text", widget: "markdown" },
              {
                label: "Videos",
                name: "items",
                widget: "list",
                summary: "{{fields.title}}",
                fields:
                  [
                    { label: "Title", name: "title", widget: "string" },
                    { label: "Video", name: "video", widget: "file", choose_url: false, pattern: ['[a-z|_-]*\.mp4', "only mp4"] },
                  ],
              },
            ],
        }
      - {
          label: "FAQ",
          name: "faq",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              { label: "Text", name: "text", widget: "markdown", required: false },
              {
                label: "Items",
                name: "items",
                widget: "list",
                summary: "{{fields.title}}",
                fields:
                  [
                    { label: "Title", name: "title", widget: "string" },
                    { label: "Text", name: "text", widget: "markdown" },
                  ],
              },
            ],
        }
      - {
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        required: false
        }
      - {
        label: "SEO Description",
        name: "summary",
        widget: "text",
        required: false
        }
      - {
        label: "SEO Keywords",
        name: "seoKeywords",
        widget: "string",
        required: false
        }

  - name: "Abfahrtsanzeige"
    label: "Abfahrtsanzeige"
    folder: "content/departures"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Intro",
          name: "intro",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Text", name: "text", widget: "markdown" },
              { label: "Button Label", name: "buttonLabel", widget: "string" },
              { label: "Button Link", name: "buttonHref", widget: "string" },
            ],
        }
      - { label: "Content", name: "body", widget: "markdown" }
      - {
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        required: false
        }
      - {
        label: "SEO Description",
        name: "summary",
        widget: "text",
        required: false
        }
      - {
        label: "SEO Keywords",
        name: "seoKeywords",
        widget: "string",
        required: false
        }

  - name: "Ereignismeldungen"
    label: "Ereignismeldungen"
    folder: "content/incidents"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Intro",
          name: "intro",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Text", name: "text", widget: "markdown" },
              { label: "Button Label", name: "buttonLabel", widget: "string" },
              { label: "Button Link", name: "buttonHref", widget: "string" },
            ],
        }
      - { label: "Content", name: "body", widget: "markdown" }
      - {
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        required: false
        }
      - {
        label: "SEO Description",
        name: "summary",
        widget: "text",
        required: false
        }
      - {
        label: "SEO Keywords",
        name: "seoKeywords",
        widget: "string",
        required: false
        }

  - name: "Fahrplan"
    label: "Fahrplan"
    folder: "content/schedule"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Intro",
          name: "intro",
          collapsed: true,
          widget: "object",
          fields:
            [
              { label: "Text", name: "text", widget: "markdown" },
              { label: "Button Label", name: "buttonLabel", widget: "string" },
              { label: "Button Link", name: "buttonHref", widget: "string" },
            ],
        }
      - { label: "Content", name: "body", widget: "markdown", required: false }
      - {
          label: "Labels",
          name: "labels",
          create: false,
          delete: false,
          collapsed: true,
          widget: "object",
          fields:
            [
              {label: "Von", name: "start", widget: "string"},
              {label: "Bis", name: "end", widget: "string"},
              {label: "Suchen", name: "search", widget: "string"},
              {label: "Alle Eingabefelder anzeigen", name: "show_all", widget: "string"},
            ],
        }
      - {
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        required: false
        }
      - {
        label: "SEO Description",
        name: "summary",
        widget: "text",
        required: false
        }
      - {
        label: "SEO Keywords",
        name: "seoKeywords",
        widget: "string",
        required: false
        }

  - name: "Contact"
    label: "Contact"
    folder: "content/contact"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
      - {
          label: "Labels",
          name: "labels",
          create: false,
          delete: false,
          collapsed: true,
          widget: "object",
          fields:
            [
              {label: "Fullname", name: "fullname", widget: "string"},
              {label: "Email", name: "email", widget: "string"},
              {label: "Phone", name: "phone", widget: "string"},
              {label: "Message", name: "message", widget: "string"},
              {label: "Send", name: "send", widget: "string"},
            ],
        }