define:
  - &title { label: "Title", name: "title", widget: "string" }
  - &body {
      label: "Content",
      name: "body",
      widget: "markdown",
      required: false,
    }
  - &text { label: "Text", name: "text", widget: "markdown" }
  - &seoTitle {
      label: "SEO Title",
      name: "seoTitle",
      widget: "string",
      required: false,
    }
  - &seoDescription {
      label: "SEO Description",
      name: "summary",
      widget: "text",
      required: false,
    }
  - &seoKeywords {
      label: "SEO Keywords",
      name: "seoKeywords",
      widget: "string",
      required: false,
    }
  - &image { label: "Image", name: "image", widget: "image", choose_url: false }
  - &intro {
      label: "Intro",
      name: "intro",
      collapsed: true,
      widget: "object",
      fields:
        [
          *text,
          {
            label: "Button Label",
            name: "buttonLabel",
            widget: "string",
            required: false,
          },
          {
            label: "Button Link",
            name: "buttonHref",
            widget: "string",
            required: false,
          },
        ],
    }
  - &tus {
      label: "TUS",
      name: "tus",
      widget: "list",
      collapsed: true,
      summary: "{{fields.title}}",
      fields: [*title, *image, { label: "url", name: "url", widget: "string" }],
    }
  - &labelsFahrplan {
      label: "Labels",
      name: "labels",
      create: false,
      delete: false,
      collapsed: true,
      widget: "object",
      fields:
        [
          { label: "Von", name: "start", widget: "string" },
          { label: "Bis", name: "end", widget: "string" },
          { label: "Suchen", name: "search", widget: "string" },
          {
            label: "Alle Eingabefelder anzeigen",
            name: "show_all",
            widget: "string",
          },
        ],
    }
  - &labels_contact {
      label: "Labels",
      name: "labels",
      create: false,
      delete: false,
      collapsed: true,
      widget: "object",
      fields:
        [
          { label: "Fullname", name: "fullname", widget: "string" },
          { label: "Email", name: "email", widget: "string" },
          { label: "Phone", name: "phone", widget: "string" },
          { label: "Message", name: "message", widget: "string" },
          { label: "Send", name: "send", widget: "string" },
        ],
    }
  - &carousel {
      label: "Carousel",
      name: "carousel",
      widget: "list",
      collapsed: true,
      summary: "{{fields.title}}",
      fields:
        [
          *title,
          *text,
          *image,
          { label: "LinkHref", name: "linkHref", widget: "string" },
          { label: "LinkLabel", name: "linkLabel", widget: "string" },
        ],
    }
  - &services {
      label: "Services",
      name: "services",
      widget: "object",
      collapsed: true,
      summary: "{{fields.title}}",
      fields:
        [
          *title,
          *text,
          {
            label: "Items",
            name: "items",
            collapsed: true,
            widget: "list",
            fields:
              [
                *title,
                *text,
                *image,
                { label: "LinkHref", name: "linkHref", widget: "string" },
                { label: "LinkLabel", name: "linkLabel", widget: "string" },
              ],
          },
        ],
    }
  - &introApp {
      label: "Intro",
      name: "intro",
      collapsed: true,
      widget: "object",
      fields:
        [
          *text,
          {
            label: "Link Android",
            name: "appLinkAndroid",
            widget: "string",
            required: false,
          },
          {
            label: "Link iOS",
            name: "appLinkIOS",
            widget: "string",
            required: false,
          },
        ],
    }
  - &videos {
      label: "Videos",
      name: "video",
      collapsed: true,
      widget: "object",
      fields:
        [
          *title,
          *text,
          {
            label: "Videos",
            name: "items",
            widget: "list",
            summary: "{{fields.title}}",
            fields:
              [
                *title,
                {
                  label: "Video",
                  name: "video",
                  widget: "file",
                  choose_url: false,
                  pattern: ['[a-z|_-]*\.mp4', "only mp4"],
                },
              ],
          },
        ],
    }
  - &faq {
      label: "FAQ",
      name: "faq",
      collapsed: true,
      widget: "object",
      fields:
        [
          *title,
          { label: "Text", name: "text", widget: "markdown", required: false },
          {
            label: "Items",
            name: "items",
            widget: "list",
            summary: "{{fields.title}}",
            fields: [*title, *text],
          },
        ],
    }

backend:
  name: github
  repo: ninfaj/oevplus-ch
  branch: master # Branch to update (optional; defaults to master)
locale: "de"
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "Home"
    label: "Home"
    folder: "content/home"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - *title
      - *intro
      - *carousel
      - *services
      - *body
      - *seoTitle
      - *seoDescription
      - *seoKeywords

  - name: "About"
    label: "About"
    folder: "content/about"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - *title
      - *intro
      - *tus
      - *body
      - *seoTitle
      - *seoDescription
      - *seoKeywords

  - name: "App"
    label: "App"
    folder: "content/app"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - *title
      - *introApp
      - *body
      - *videos
      - *faq
      - *seoTitle
      - *seoDescription
      - *seoKeywords

  - name: "Abfahrtsanzeige"
    label: "Abfahrtsanzeige"
    folder: "content/departures"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - *title
      - *intro
      - *body
      - *seoTitle
      - *seoDescription
      - *seoKeywords

  - name: "Ereignismeldungen"
    label: "Ereignismeldungen"
    folder: "content/incidents"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - *title
      - *intro
      - *body
      - *seoTitle
      - *seoDescription
      - *seoKeywords

  - name: "Fahrplan"
    label: "Fahrplan"
    folder: "content/schedule"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - *title
      - *intro
      - *body
      - { <<: *labelsFahrplan }
      - *seoTitle
      - *seoDescription
      - *seoKeywords

  - name: "Contact"
    label: "Contact"
    folder: "content/contact"
    summary: "{{filename}} – {{fields.title}}"
    create: false
    delete: false
    fields: # The fields for each document, usually in front matter
      - *title
      - *body
      - { <<: *labels_contact }
