backend:
  name: github
  repo: ninfaj/oevplus-ch
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "pages"
    label: "Pages" # Used in the UI
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          required: false,
          choose_url: false,
          editor: { preview: false },
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Sections",
          name: "sections",
          widget: "list",
          summary: "{{fields.title}} ({{fields.color}})",
          fields:
            [
              {
                label: "Farbe",
                name: "color",
                widget: "select",
                options:
                  [
                    { label: "Weiss", value: "white" },
                    { label: "Grau", value: "light" },
                    { label: "Blau", value: "blue" },
                    { label: "Dunkelblau", value: "darkblue" },
                  ],
              },
              { label: "CSS Klasse", name: "class", widget: "string", required: false },
              { label: "Title", name: "title", widget: "string", required: false },
              { label: "Body", name: "body", widget: "markdown" },
            ],
        }
  - name: "faq"
    label: "FAQ" # Used in the UI
    folder: "content/faq" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: { field: "editable", value: true }
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "editable", name: "editable", widget: "hidden", default: true }
      - { label: "position", name: "weight", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
